@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=5
&offset=1

### Lista apenas um recado
GET {{baseUrl}}/recados/18/

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo recado teste",
    "deId": 7,
    "paraId": 1
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/30/
Content-Type: application/json

{
    "texto": "de lelezinha para Robertão Gostosão"
}

### Apaga um recado
DELETE {{baseUrl}}/recados/29/



#



# PESSOAS
### Lista todos as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0

### Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/8/

### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "robertinho3@orkut.com",
    "password": "123456",
    "nome": "Roberto"
}

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/9/
Content-Type: application/json

{
    "password": "55555",
    "nome": "Elisabeth"
}

### Apaga uma pessoa
DELETE {{baseUrl}}/pessoas/8/